# Generated by Django 2.1.2 on 2018-11-23 19:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ocean', '0002_auto_20181123_2216'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='is_active',
            new_name='active',
        ),
    ]
