# Generated by Django 2.1.2 on 2018-11-24 07:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ocean', '0003_auto_20181123_2236'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='company',
            field=models.IntegerField(default=0, verbose_name='компания'),
        ),
    ]
